# Generated by Django 2.1.2 on 2018-11-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='topic',
        ),
        migrations.AddField(
            model_name='entry',
            name='topic',
            field=models.ManyToManyField(to='logs.Topic'),
        ),
    ]
