# Generated by Django 2.1.2 on 2018-11-17 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20181116_2213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Fruit',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
