# Generated by Django 2.1.2 on 2018-11-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20181117_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruit',
            name='id',
        ),
        migrations.AlterField(
            model_name='fruit',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
